/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: HeyNinety (https://sketchfab.com/HeyNinety)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/dog-c1d790c39dcf4ba2a9a47b4c0dc8836b
title: Dog
*/

import React, { useRef } from 'react'
import { Canvas, useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/dog.gltf')
  useFrame((state, delta) => (group.current.rotation.y += 0.01))
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.3, 0.09, 0]} scale={0.53}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.fur_light} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.eye1} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.eye2} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.fur_dark} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.tongue} />
            <mesh geometry={nodes.Object_9.geometry} material={materials.outline} />
          </group>
          <group position={[-0.3, 0.09, 0]} scale={0.53}>
            <mesh geometry={nodes.Object_11.geometry} material={materials.outline} />
          </group>
          <group position={[-0.71, -0.06, 0]}>
            <mesh geometry={nodes.Object_13.geometry} material={materials.outline} />
          </group>
          <group position={[0.1, -0.65, 0]}>
            <mesh geometry={nodes.Object_15.geometry} material={materials.griptape} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.wood} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.metal} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.wheel} />
            <mesh geometry={nodes.Object_19.geometry} material={materials['wheel.001']} />
          </group>
          <group position={[0.1, -0.65, 0]}>
            <mesh geometry={nodes.Object_21.geometry} material={materials.material_0} />
          </group>
          <group position={[0.1, -0.65, 0]}>
            <mesh geometry={nodes.Object_23.geometry} material={materials['outline.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dog.gltf')
